steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-f', './dockerfiles/trainer.dockerfile', '-t', 'gcr.io/dtumlops1/image-docker', '.', '--no-cache']
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/dtumlops1/image-docker']
