'gcr.io/cloud-builders/docker'
['build', '-f', './dockerfile/trainer.dockerfile', '-t', 'gcr.io/dtumlops1/image-docker', '.', 'no-cache']
'gcr.io/cloud-builders/docker'
['push', 'gcr.io/dtumlops1/image-docker']
