steps:
    - name: 'gcr.io/cloud-builders/docker'
        args: ['build', '-t', 'gcr.io/dtumlops1/image-docker', '.']
    - name: 'gcr.io/cloud-builders/docker'
        args: ['push', 'gcr.io/dtumlops1/image-docker']